services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


  Localfr\AgendizeClientBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../Tests/'

  localfr.agendize.serializer:
    class: Localfr\AgendizeClientBundle\Component\Serializer\AgendizeSerializer
    public: true

  localfr.agendize.agendize_provider:
    class: Localfr\AgendizeClientBundle\Service\Agendize\AuthProvider\AgendizeProvider
    public: true
    arguments:
      $apiKey: '%localfr_agendize.api_key%'
      $apiToken: '%localfr_agendize.api_token%'

  localfr.agendize.cached_agendize_provider:
    class: Localfr\AgendizeClientBundle\Service\Agendize\AuthProvider\CachedAgendizeProvider
    public: true
    arguments:
      $apiKey: '%localfr_agendize.api_key%'
      $apiToken: '%localfr_agendize.api_token%'

  Localfr\AgendizeClientBundle\Service\Agendize\Client\AgendizeClient:
    arguments:
      $apiVersion: '%localfr_agendize.api_version%'

  localfr.agendize.client:
    public: true
    class: Localfr\AgendizeClientBundle\Service\Agendize\Client\AgendizeClient
    arguments:
      $apiVersion: '%localfr_agendize.api_version%'
  
  Localfr\AgendizeClientBundle\Service\Agendize\AuthProvider\AgendizeProviderInterface: '@localfr.agendize.cached_agendize_provider'
